sidebar:
  en:
    - label: "Home"
      link: "/"

    - label: "Getting Started"
      items:
        - label: "Installation"
          link: "installation"
        - label: "First Steps"
          link: "first-steps"
        - label: "API Marketplace Overview"
          link: "marketplace-overview"

    - label: "API Management"
      items:
        - label: "Creating APIs"
          link: "creating-apis"
        - label: "Managing APIs"
          link: "managing-apis"
        - label: "API Documentation"
          link: "api-documentation"

    - label: "User Guide"
      items:
        - label: "Authentication"
          link: "authentication"
        - label: "Billing and Subscriptions"
          link: "billing-subscriptions"
        - label: "Support"
          link: "support"

  fr:
    - label: "Accueil"
      link: "/"

    - label: "Commencer"
      items:
        - label: "Installation"
          link: "installation"
        - label: "Premiers Pas"
          link: "premiers-pas"
        - label: "Vue d ensemble du marché d API"
          link: "vue-densemble-marche-api"

    - label: "Gestion d API"
      items:
        - label: "Créer des API"
          link: "creer-apis"
        - label: "Gérer des API"
          link: "gerer-apis"
        - label: "Documentation API"
          link: "documentation-api"

    - label: "Guide d utilisation"
      items:
        - label: "Authentification"
          link: "authentification"
        - label: "Facturation et Abonnements"
          link: "facturation-abonnements"
        - label: "Support"
          link: "support"
